[package]
name = "mp8"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
ndarray = "0.15"
ndarray-stats = "0.4" 
sysinfo = "0.24.4"